language: go

go:
- 1.14.x

go_import_path: github.com/gemalto/helm-image

install:

script:
- make dist

deploy:
- provider: releases
  api_key: ${GITHUB_TOKEN}
  file: _dist/helm-image*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
