name: "image"
version: 1.0.7
usage: "get docker images from a chart"
description: "Helm plugin for getting docker images from a chart"
command: "$HELM_PLUGIN_DIR/bin/helm-image"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
