name: Release on github
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/src/github.com/cvila84/helm-image
      - name: Make release
        run: |
          cd ${{ github.workspace }}/src/github.com/cvila84/helm-image
          make dist
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: ${{ github.workspace }}/src/github.com/cvila84/helm-image/_dist/helm-image*
